Mo/data api
HorizenOfficial/rosetta-zen pull request #1
Opened 2020-10-22 13:02 UTC by MarcoOl94

Fixes # .

### Motivation

### Solution

### Open questions

2020-10-22 16:55 UTC, albertog78 requested changes

2020-10-22 16:55 UTC, albertog78 commented on assets/zen-mainnet.conf
> +prune=550
Rosetta bitcoin seems to be designed for manual pruning (not supported by zend). Let's disable it (also in the code)

2020-10-22 16:55 UTC, albertog78 commented on main.go
> +	maxHeapUsage = 1000 // ~8.5 GB
Disable Prune schedule (https://github.com/HorizenOfficial/rosetta-zen/pull/1/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R113)

2020-10-22 16:55 UTC, albertog78 commented on README.md
> -## Architecture
restore schema

2020-10-22 16:55 UTC, albertog78 commented on assets/zen-testnet.conf
> +txindex=1
this should not be necessary. Is it?

2020-10-22 16:55 UTC, albertog78 commented on README.md
> +© 2020 Horizen
© 2020 Coinbase
© 2020 Zen Blockchain Foundation

2020-10-22 16:55 UTC, albertog78 commented on btcd/chaincfg/params.go
> +type Params struct {
Remove params not applicable to our network

2020-10-22 16:55 UTC, albertog78 commented on btcd/txscript/standard.go
> +func isMultiSig(pops []parsedOpcode) bool {
Add also isMultiSigReplay

2020-10-22 16:55 UTC, albertog78 commented on btcd/wire/msgtx.go
> +func (msg *MsgTx) WitnessHash() chainhash.Hash {
rename to TxHash

2020-10-22 16:55 UTC, albertog78 commented on btcutil/tx.go
> +func (t *Tx) WitnessHash() *chainhash.Hash {
remove this

2020-10-22 16:55 UTC, albertog78 commented on services/construction_service.go
> +		if (class == txscript.NonStandardTy) {
allow only PubKeyHashReplay addresses

2020-10-22 16:55 UTC, albertog78 commented on services/construction_service.go
> +		if (class == txscript.NonStandardTy) {
same as above

2020-10-23 16:36 UTC, albertog78 requested changes

2020-10-23 16:36 UTC, albertog78 commented on services/construction_service.go
> +	size := zen.TransactionOverhead
Modify this function to calculate the size taking in consideration Replay protection etc ..
Introduce a test to verify correctness

2020-10-23 16:36 UTC, albertog78 commented on services/construction_service.go
>  			script, err := txscript.PayToAddrScript(addr)
PayToAddrScriptReplayOut

2020-10-23 16:36 UTC, albertog78 commented on zen/client.go
> +func (b *Client) GetHashFromIndex(
In parseTransactions exclude coinbase miner reward transaction that are not spendable with transparent txs

2020-10-26 19:22 UTC, albertog78 requested changes

2020-10-26 19:22 UTC, albertog78 commented on zen/client.go
> +	if b.genesisBlockIdentifier.Hash == MainnetGenesisBlockIdentifier.Hash {
remove this

2020-10-26 19:22 UTC, albertog78 commented on zen/client.go
> +		if (index != 0) || (b.genesisBlockIdentifier.Hash != MainnetGenesisBlockIdentifier.Hash) {
index all txs

2020-10-26 19:27 UTC, albertog78 approved these changes

2020-10-27 17:00 UTC, cronicc commented on services/account_service.go
> +	var filtered_coin []*types.Coin
```
services/account_service.go:57:6: don't use underscores in Go names; var filtered_coin should be filteredCoin
Found 1 lint suggestions; failing.
```

2020-10-29 19:32 UTC, cronicc commented
Superseded by #3

2020-10-29 19:32 UTC, closed without merging