feat: zen 4.1.0-rc0 (deprecates shielded txs)
HorizenOfficial/rosetta-zen pull request #38
Opened 2023-08-04 20:55 UTC by voyenavion

2023-08-04 20:59 UTC, rabyyuson approved these changes

2023-08-07 17:01 UTC, cronicc requested changes

2023-08-07 17:01 UTC, cronicc commented on Dockerfile
> +ARG ZEN_COMMITTISH=v4.1.0-rc0
```suggestion
# Latest release zen 4.1.0-rc1
ARG ZEN_COMMITTISH=v4.1.0-rc1
```

2023-08-07 17:01 UTC, cronicc commented on services/network_service_test.go
> +			NodeVersion:       "4.1.0-rc0",
```suggestion
			NodeVersion:       "4.1.0-rc1",
```

2023-08-07 17:01 UTC, cronicc commented on services/types.go
> +	NodeVersion = "4.1.0-rc0"
```suggestion
	NodeVersion = "4.1.0-rc1"
```

2023-08-07 17:02 UTC, cronicc approved these changes

2023-08-07 18:26 UTC, merged